src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Bucket_Name__c</fullName>
        <label>Bucket Name</label>
        <length>122</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>image/gif</fullName>
                </value>
                <value>
                    <fullName>image/jpeg</fullName>
                </value>
                <value>
                    <fullName>image/png</fullName>
                </value>
                <value>
                    <fullName>text/html</fullName>
                </value>
                <value>
                    <fullName>text/plain</fullName>
                </value>
                <value>
                    <fullName>gif</fullName>
                </value>
                <value>
                    <fullName>pdf</fullName>
                </value>
                <value>
                    <fullName>jpg</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>AWS S3 Object</label>
    <nameField>
        <displayFormat>AWS-{0000}</displayFormat>
        <label>AWS S3 Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AWS S3 Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Image_Upload__e.object
<CustomObject>
    <description>An event that highlights a new image has been uploaded.</description>
    <fields>
        <fullName>RecordId__c</fullName>
        <description>The Record Id of the image being stored. Linked record contains base metadata around the image.</description>
        <label>RecordId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_URL__c</fullName>
        <description>The S3 URL for the image we have uploaded.</description>
        <label>S3 URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Image Upload</label>
    <pluralLabel>Image Uploads</pluralLabel>
</CustomObject>

src/classes/S3PlatformEventGenerator.cls
public with sharing class S3PlatformEventGenerator {
	@InvocableMethod(label='Create S3 Upload Patform Event' description='Creates a platform event that signifies the S3 image has been uploaded')
	public static void createEvents(List<AWS_S3_Object__c> s3Objects) {

		List<Image_Upload__e> uploads = new List<Image_Upload__e>();

		for(AWS_S3_Object__c s3Obj : s3Objects) {		
			Image_Upload__e upload = new Image_Upload__e();
			upload.S3_URL__c = 'https://s3-us-west-1.amazonaws.com/' + s3Obj.Bucket_Name__c + '/' + s3Obj.File_Name__c;
			upload.RecordId__c = s3Obj.Id;	
			uploads.add(upload);
		}
		
		EventBus.publish(uploads);

	}

	public static void demoTime(Id s3ObjectId) {
		createEvents([SELECT Id, Bucket_Name__c, File_Name__c, Content_Type__c FROM AWS_S3_Object__c WHERE Id = :s3ObjectId]);
	}
}